name: opencode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
    
jobs:
  opencode:
    if: |
      (contains(github.event.comment.body, '/oc') || contains(github.event.comment.body, '/opencode')) &&
      github.event.comment.user.type == 'User' &&
      github.event.comment.user.login != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
       - name: Checkout repository
         uses: actions/checkout@v6
         with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true
       - name: Configurar identidad de Git
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
       - name: Run OpenCode
         uses: anomalyco/opencode/github@latest
         env:
           DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
           GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
         with:
           model: azure/zai-org--glm-47-fp8
           share: true
           use_github_token: true
